name: Terraform AWS MLOps Deployment

on:
  workflow_dispatch:
#  push:
#    branches: [ main ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package Lambda
        run: |
          cd terraform-mlops/lambda
          zip -r ../lambda.zip retrain_trigger.py
          
      - name: Terraform Init
        run: cd terraform-mlops && terraform init

      - name: Terraform Format Check
        run: cd terraform-mlops && terraform fmt -check

      - name: Terraform Validate
        run: cd terraform-mlops && terraform validate

      - name: Terraform Plan
        run: cd terraform-mlops && terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: cd terraform-mlops && terraform apply -auto-approve tfplan
